FROM rust:1.25 as build

WORKDIR /usr/src/queue

ADD ./queue/Cargo.toml Cargo.toml

ADD ./queue/src src

WORKDIR /usr/src/web

ADD ./web/Cargo.toml Cargo.toml

ADD ./web/src src

RUN cargo build --release

FROM rust:1.25
RUN useradd -m iron
USER iron

WORKDIR /web
COPY --from=build /usr/src/web/target/release/web .

CMD [ "/bin/bash", "-c", "env && ls -al && ./web" ]
