apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert -c
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "web"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
